name: playground

on:
  push:
    paths:
      - "playground/**"

jobs:
  lint:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playground
    steps:
      - uses: actions/checkout@v3
      - name: setup bun runtime
        uses: antongolub/action-setup-bun@v1 # or @v1.x.x
      - name: install bun dependencies
        run: bun install
      - name: run lint
        run: bun run lint
