name: playground

on:
  push:
    paths:
      - "playground/**"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playground
    steps:
      - uses: actions/checkout@v3
      - name: setup bun runtime
        uses: antongolub/action-setup-bun@v1
        with:
          platform: 'darwin'
          arch: 'arm64'
      - name: install bun dependencies
        run: bun install
      - name: run lint
        run: bun run lint
