snowflake_emulator:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: test_account
      user: test_user
      password: test_password
      database: test_db
      schema: public
      warehouse: test_wh
      host: localhost
      port: 8080
      protocol: http
